Repository AY2425S1-CS2103T-F09-1/tp, pull requests merged in 2024-11, with the labels that each got.

#114 Split DeleteCommand.java to account for delete by name and index
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteByIndexCommand.java
  src/main/java/seedu/address/logic/commands/DeleteByNameCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteByIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteByNameCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.Medium

#117 Update sample address book to contain some events
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/SampleAddressBookTest.java
Labels: priority.Medium

#121 Add unassign_event command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/UnassignEventByPersonIndexEventIndexCommand.java
  src/main/java/seedu/address/logic/commands/UnassignEventByPersonIndexEventNameCommand.java
  src/main/java/seedu/address/logic/commands/UnassignEventByPersonNameEventIndexCommand.java
  src/main/java/seedu/address/logic/commands/UnassignEventByPersonNameEventNameCommand.java
  src/main/java/seedu/address/logic/commands/UnassignEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/UnassignEventCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignEventByPersonIndexEventIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignEventByPersonIndexEventNameCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignEventByPersonNameEventIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignEventByPersonNameEventNameCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UnassignEventCommandParserTest.java
  src/test/java/seedu/address/testutil/EventUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#118 Update ID counter list initialisation
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/SampleAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#115 Add delete event command
  src/main/java/seedu/address/logic/commands/DeleteEventByIndexCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventByNameCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteEventByIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteEventByNameCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEventCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
Labels: priority.High

#125 Update delete event command to delete the event from all persons
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: priority.High

#127 Update User Guide to include delete event command
  docs/UserGuide.md
Labels: priority.High

#141 Change addressbook.json to clubconnect.json
  docs/UserGuide.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#136 Fix jar file name in shadowJar
  build.gradle
Labels: type.Bug, severity.VeryLow, alpha-bug

#135 Fix GUI window title name
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.VeryLow, alpha-bug

#132 Update command summary
  docs/UserGuide.md
Labels: priority.High

#139 Update search section in User Guide
  docs/UserGuide.md
Labels: alpha-bug

#143 Change Event names to be case-insensitive
  src/main/java/seedu/address/model/event/Event.java
  src/test/java/seedu/address/logic/commands/DeleteEventByNameCommandTest.java
  src/test/java/seedu/address/model/event/EventTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#146 Remove traces of AB3 in logs
  src/main/java/seedu/address/MainApp.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#151 Remove traces of AB3 in user guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: severity.High, alpha-bug

#153 Update Person's name to be case-insensitive
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/DeleteByNameCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignEventByPersonNameEventIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignEventByPersonNameEventNameCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: severity.Low, alpha-bug

#154 Update UG with unassign_event command
  docs/UserGuide.md
Labels: priority.High

#156 Update delete event command word
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
Labels: severity.Low, alpha-bug

#158 Update user guide to match new delete event command word
  docs/UserGuide.md
Labels: severity.Low, alpha-bug

#123 Change edit event to target index
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditEventCommandParserTest.java
Labels: priority.High

#148 Add assign_event command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignEventByPersonIndexEventIndexCommand.java
  src/main/java/seedu/address/logic/commands/AssignEventByPersonIndexEventNameCommand.java
  src/main/java/seedu/address/logic/commands/AssignEventByPersonNameEventIndexCommand.java
  src/main/java/seedu/address/logic/commands/AssignEventByPersonNameEventNameCommand.java
  src/main/java/seedu/address/logic/commands/AssignEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignEventCommandParser.java
  src/test/java/seedu/address/logic/commands/AssignEventByPersonIndexEventIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignEventByPersonIndexEventNameCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignEventByPersonNameEventIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignEventByPersonNameEventNameCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/EventUtil.java
Labels: priority.High

#164 Update UG to follow new delete event command word
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/AssignEventByPersonNameEventIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignEventByPersonNameEventNameCommandTest.java
Labels: severity.Low

#169 Update UG with assign_event command
  docs/UserGuide.md
Labels: priority.High

#171 Update message usage for import command
  src/main/java/seedu/address/logic/commands/ImportCommand.java
Labels: alpha-bug

#176 Modify import command to check if file to import contacts from is a csv file
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: alpha-bug

#178 Modify MESSAGE_USAGE string
  src/main/java/seedu/address/logic/commands/SearchCommand.java
Labels: alpha-bug

#182 Remove unused method in ParserUtil class
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: alpha-bug

#179 Modify export command to throw command exception
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: alpha-bug

#180 Update export command and import command sections of user guide
  docs/UserGuide.md
Labels: alpha-bug

#184 Modify user guide to show new behaviour of v1.5 for search command
  docs/UserGuide.md
Labels: priority.Low

#168 Edit user guide
  docs/UserGuide.md
Labels: type.Task, priority.Low

#166 Change ID to indexes
  src/main/java/seedu/address/logic/commands/MassDeleteCommand.java
Labels: severity.VeryLow

#242 Fix repetitive instructions for assign and unassign commands
  docs/UserGuide.md
Labels: ug-bug

#241 Fix repo link
  docs/_markbind/layouts/default.md
Labels: ug-bug

#239 Fix webpage header
  docs/site.json
Labels: ug-bug, dg-bug

#243 Fix minor issue in known issues of the UG
  docs/UserGuide.md
Labels: ug-bug

#244 Add tips to the UG for readers to let them know what is a displayed list
  docs/UserGuide.md
Labels: ug-bug

#245 Update DG's Planned Enhancement
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: dg-bug

#247 Remove AB3 links in DG
  docs/DeveloperGuide.md
Labels: dg-bug

#249 Add use cases for add_event and unassign_event
  docs/DeveloperGuide.md
Labels: priority.Medium

#253 Add manual test cases
  docs/DeveloperGuide.md
Labels: priority.Medium

#254 Fix UI Class Diagram
  docs/diagrams/UiClassDiagram.puml
Labels: dg-bug

#250 Split commands into sections
  docs/UserGuide.md
Labels: priority.Medium

#263 Update export section of user guide
  docs/UserGuide.md
Labels: ug-bug

#262 Update import section of user guide
  docs/UserGuide.md
Labels: ug-bug

#266 Add UI images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addEventResult.png
  docs/images/addJohnDoeResult.png
  docs/images/assignEventResult.png
  docs/images/clearMessage.png
  docs/images/deleteEventResult.png
  docs/images/deleteJohnDoeResult.png
  docs/images/editAlexYeohResult.png
  docs/images/editEventResult.png
  docs/images/exportContactsResult.png
  docs/images/findAlexDavidResult.png
  docs/images/importContactsResult.png
  docs/images/list.png
  docs/images/listEventsResult.png
  docs/images/massDeleteResult.png
  docs/images/searchOrbitalWorkshopResult.png
  docs/images/unassignEventResult.png
Labels: ug-bug

#260 Modify method to deal with multiple whitespaces between keywords
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug

#257 Update search section in user guide
  docs/UserGuide.md
  docs/images/searchEventOrbitalWorkshop.png
  docs/images/searchTagsFriendsResult.png
Labels: ug-bug

#256 Reflect new behaviour of find command in User Guide
  docs/UserGuide.md
Labels: ug-bug

#268 Add user story for edit event
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: dg-bug

#270 Fix bug on mass delete
  src/main/java/seedu/address/logic/commands/MassDeleteCommand.java
Labels: severity.Low

#273 Update command summary for search command
  docs/UserGuide.md
Labels: ug-bug

#279 Add planned enhancements
  docs/DeveloperGuide.md
Labels: dg-bug

#282 Add manual testing instructions for search command
  docs/DeveloperGuide.md
Labels: dg-bug

#285 Edit event bug
  docs/DeveloperGuide.md
Labels: dg-bug

#283 Fix bug where event prefix is used with a blank
  src/main/java/seedu/address/logic/commands/SearchCommand.java
Labels: type.Bug

#286 Edit font in dg
  docs/DeveloperGuide.md
Labels: dg-bug

#288 Update DG format for import export manual test cases
  docs/DeveloperGuide.md
Labels: dg-bug

#289 Add spaces
  docs/DeveloperGuide.md
Labels: dg-bug

#290 Update DG for search manual test cases
  docs/DeveloperGuide.md
Labels: dg-bug
