Repository AY2425S1-CS2103T-F09-1/tp, pull requests merged in 2024-10, with the labels that each got.

#51 Fix README.md bug
  README.md
Labels: type.Bug

#57 Fix README.md bug (Traces of AB3 remain)
  README.md
Labels: type.Bug

#61 Delete by name Feature
  docs/package-lock.json
  docs/package.json
  package-lock.json
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: priority.High

#63 Add "Event" class
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventDescription.java
  src/main/java/seedu/address/model/event/EventDuration.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/event/EventDescriptionTest.java
  src/test/java/seedu/address/model/event/EventDurationTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.High

#62 Add mass delete feature
  src/main/java/seedu/address/logic/commands/MassDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MassDeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/MassDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/MassDeleteCommandParserTest.java
Labels: priority.High

#67 Add export to csv feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
Labels: priority.Medium

#71 Add ID counters for persons and events to JSON file
  .gitignore
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/id/counter/list/IdCounterList.java
  src/main/java/seedu/address/storage/JsonAdaptedIdCounterList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#75 Add filter function to mass delete
  src/main/java/seedu/address/logic/commands/MassDeleteCommand.java
  src/main/java/seedu/address/logic/parser/MassDeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/MassDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/MassDeleteCommandParserTest.java
Labels: priority.Medium

#69 Add testcases for ExportCommand
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/data/CsvTest/ExpectedExportedContacts.csv
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: priority.Medium

#77 Add support for tags in Search command
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
Labels: priority.High

#79 Import command
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/CsvTest/ExpectedExportedContacts.csv
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
Labels: priority.Medium

#82 Fix bug in Events
  src/main/java/seedu/address/model/AddressBook.java
Labels: type.Bug, severity.High

#84 Add list_events command
  .vscode/settings.json
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListEventsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListEventsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/EventUtil.java
Labels: priority.High

#95 Update User Guide with import and export features
  docs/UserGuide.md
Labels: type.Task

#97 Update user guide with mass delete
  docs/UserGuide.md
Labels: type.Task

#93 Add search command section to User Guide
  docs/UserGuide.md
Labels: type.Task

#89 Replace AB3 link in help window
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#87 Update user guide with add_event and list_event features
  docs/UserGuide.md
Labels: type.Task

#91 Update UML diagrams with Event class
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task

#105 Modify search command format
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Labels: priority.Medium

#99 Add edit event function
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditEventCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/EventUtil.java
Labels: priority.Medium

#111 Create UML sequence diagram for Search commands
  docs/diagrams/SearchSequenceDiagram.puml
Labels: type.Task
